name: test
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'run workflow using api'
        default: 'test'
        required: true

env:
  var_1: "valueofvar1"

jobs:
  test_flow:
    runs-on: ubuntu-latest
    steps:

      - name: check out action
        uses: actions/checkout@v2
        
      - name: run test
        run: bash script/commit.bash
   
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}
